apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpaas-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rpaas-api
  template:
    metadata:
      labels:
        name: rpaas-api
    spec:
      serviceAccountName: rpaas-operator
      containers:
        - name: rpaas-api
          image: 10.200.10.1:5000/tsuru/rpaas-api
          ports:
          - containerPort: 9999
            name: api
          command:
          - rpaas-api
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rpaas-api
spec:
  ports:
  - name: api
    port: 9999
    targetPort: 9999
  selector:
    name: rpaas-api
  type: NodePort
