apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rpaasinstances.extensions.tsuru.io
spec:
  group: extensions.tsuru.io
  names:
    kind: RpaasInstance
    listKind: RpaasInstanceList
    plural: rpaasinstances
    singular: rpaasinstance
  scope: Namespaced
  version: v1alpha1
