apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpaas-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rpaas-operator
  template:
    metadata:
      labels:
        name: rpaas-operator
    spec:
      serviceAccountName: rpaas-operator
      containers:
        - name: rpaas-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - rpaas-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rpaas-operator"
---
apiVersion: v1
kind: Service
metadata:
  name: rpaas-operator
spec:
  ports:
  - name: api
    port: 9999
    targetPort: 9999
  selector:
    name: rpaas-operator
  type: NodePort
